Tutorials/api
jaimin45/demo-nodejs-tutorials pull request #20
Opened 2021-12-21 07:41 UTC by jaimin45

Changes According sir given !!

2021-12-21 07:46 UTC, ashishkava approved these changes

2021-12-21 07:55 UTC, JainishaParmar approved these changes

2021-12-22 04:56 UTC, kapilbarad requested changes

2021-12-22 04:56 UTC, kapilbarad commented on controllers/tutorialsControllers.js
> +    res.status(404).send();
We should specify error message here.

Pattern of error should be:
```
{
  message: 'not found'
}
```

Same pattern should be applied to all the error responses.

2021-12-22 04:56 UTC, kapilbarad commented on controllers/tutorialsControllers.js
>      res.json(tutorialUpdate);
Don't need to return anything here. Just Response with status code 203 should befine.
```
POST /tutorials - Should return 201 with newly created record.
PATCH /tutorials/:id - Should return 201 without any response.
DELETE /tutorials/:id - Should return 200 without any response.
```
CC: @ashishkava @JainishaParmar

2021-12-22 04:56 UTC, kapilbarad commented on routes/tutorials.js
> +router.patch("/:Id", updateTutorials);
Parameters should be in camel case.
`Id` should be `id`, Same for the other APIs.

2021-12-22 04:56 UTC, kapilbarad commented on swagger.yaml
> +        "200":
Missing 500 response for all the APIs.

2021-12-22 04:56 UTC, kapilbarad commented on swagger.yaml
> +        "404":
We also need to provide definition for the error response which will be common for all the APIs.

For example:
```
"404":
  description: "Tutorial not found"
  schema:
    $ref: "#/definitions/404Response"
```

Same for the 500 status code.

2021-12-22 07:39 UTC, JainishaParmar approved these changes

2021-12-22 09:56 UTC, ashishkava approved these changes

2021-12-22 12:48 UTC, kapilbarad requested changes

2021-12-22 12:48 UTC, kapilbarad commented on .eslintrc.json
> +      "no-unused-vars": "off",
Please remove below rules from here:
```
no-unused-vars
new-cap
comma-dangle

```

2021-12-22 12:48 UTC, kapilbarad commented on swagger.yaml
> +        description: ID of the tutorial that we want to find
No need of the `that we want to find` as we've this parameter common for DELETE and GET apis

2021-12-22 12:48 UTC, kapilbarad commented on swagger.yaml
> +        "201":
Patch Should have 204 response without response body Please apply the same in controller.

2021-12-22 12:48 UTC, kapilbarad commented on swagger.yaml
> +      summary: Get tutorials By ID
Typo: `Get tutorial by ID`

2021-12-22 12:48 UTC, kapilbarad commented on swagger.yaml
> +            $ref: "#/definitions/Tutorial"
While creating new Tutorial, body only needs to title and description nothing else. so we can't reference `#/definitions/Tutorial` here. We need to create another definition for example `TutorialCreateBody` with only title and description fields.

CC: @JainishaParmar @ashishkava

2021-12-22 12:48 UTC, kapilbarad commented on swagger.yaml
> +            $ref: "#/definitions/404Response"
Wrong ref.

2021-12-23 05:05 UTC, JainishaParmar approved these changes

2021-12-23 08:41 UTC, ashishkava approved these changes

2021-12-23 13:40 UTC, kapilbarad approved these changes

2021-12-23 13:41 UTC, kapilbarad approved these changes

2021-12-24 11:58 UTC, ashishkava approved these changes

2021-12-27 04:52 UTC, ashishkava approved these changes

2021-12-27 04:52 UTC, JainishaParmar approved these changes

2021-12-27 05:29 UTC, jaimin45 commented
Features/APIs

2021-12-27 05:29 UTC, merged