Validations/joi
jaimin45/demo-nodejs-tutorials pull request #22
Opened 2021-12-27 10:52 UTC by jaimin45

2021-12-27 12:05 UTC, JainishaParmar approved these changes

2021-12-28 05:31 UTC, JainishaParmar approved these changes

2021-12-28 06:35 UTC, kapilbarad requested changes

2021-12-28 06:35 UTC, kapilbarad commented on routes/users.js
> +const express = require("express");
What is this file for?

2021-12-28 06:35 UTC, kapilbarad commented on routes/index.js
> +const express = require("express");
Why we've added this fine again?

2021-12-28 06:35 UTC, kapilbarad commented on validations/tutorialsValidate.js
> +  schema,
You should name it in a way so it won't conflict with other variables, Like `postTutorialSchema` and `patchTutorialSchema`.

2021-12-28 06:35 UTC, kapilbarad commented on controllers/tutorialsControllers.js
> +    await schema.validateAsync(req.body);
Did you test by passing invalid title or any other fields? What's the response you're getting?

2021-12-28 06:35 UTC, kapilbarad commented on validations/tutorialsValidate.js
> +const joi = require("joi");
You can use `tutorial.validations.js` or just `tutorial.js` as the file name.

2021-12-28 06:35 UTC, kapilbarad commented on controllers/tutorialsControllers.js
> +    await schema.validateAsync(req.body);
Did you test by passing invalid title or any other fields? What's the response you're getting?

2021-12-28 06:35 UTC, kapilbarad commented on controllers/tutorialsControllers.js
> +    await schema.validateAsync(req.body);
This is how you should be using Joi to validate:
```
const { error, body: tutorialBody } = postTutorialSchema.validate(req.body);

# Return error response if there is anything in error variable
...
...
...
const tutorial = await Tutorial.findByIdAndUpdate(
      { _id: req.params.id },
      tutorialBody,
      { new: true }
    );
```

2021-12-28 11:02 UTC, JainishaParmar approved these changes

2021-12-29 04:32 UTC, kapilbarad commented on controllers/tutorialsControllers.js
> +    await schema.validateAsync(req.body);
@jaimin45 , Please follow this example that I shared above.

2021-12-29 04:36 UTC, kapilbarad requested changes

2021-12-29 04:36 UTC, kapilbarad commented on controllers/tutorialsControllers.js
> +    const { error, body: tutorialBody } = postTutorialSchema.validate(req.body);
We should return the error here, no need to always return error from catch block. 
```
if (error) {
   return res.status(400).send({ message: <error-detail> });
}
```

Above code will return 400 error if there will be any validation errors.

CC: @JainishaParmar @ashishkava

2021-12-29 04:36 UTC, kapilbarad commented on controllers/tutorialsControllers.js
> +      error,
Why are we passing error here?

2021-12-29 11:30 UTC, JainishaParmar approved these changes

2021-12-29 11:33 UTC, ashishkava approved these changes

2021-12-29 11:55 UTC, kapilbarad requested changes

2021-12-29 11:55 UTC, kapilbarad commented on controllers/tutorialsControllers.js
> +    if (error) {
Please verify CastError same as postTutorial API

2021-12-29 11:59 UTC, JainishaParmar approved these changes

2021-12-29 12:02 UTC, jaimin45 commented
Validations/Joi

2021-12-29 12:02 UTC, merged