feat: set Envs
jaimin45/demo-nodejs-tutorials pull request #24
Opened 2021-12-31 08:44 UTC by jaimin45

feat: Set Envs

2021-12-31 09:19 UTC, JainishaParmar approved these changes

2021-12-31 09:26 UTC, kapilbarad requested changes
- Please update Readme to add section which will explain envs.
- Add .env in .gitignore

2022-01-03 07:17 UTC, JainishaParmar approved these changes

2022-01-03 07:17 UTC, jaimin45 commented
feat: set ENVs

2022-01-03 07:18 UTC, merged