feat:Apis for user Authentication
jaimin45/demo-nodejs-tutorials pull request #25
Opened 2022-01-03 10:12 UTC by jaimin45

Added Apis user authentication.

2022-01-04 05:25 UTC, kapilbarad requested changes
Please correct below APIs:
POST `/oauth`: API to create JWT Token
POST `/oauth/forgot-password`: API to create an OTT and send to email
PATCH `/oauth/forgot-password`: API to update password using OTT
PATCH `/oauth/reset-password`: API to update password using old password

CC: @ashishkava @JainishaParmar

2022-01-04 05:25 UTC, kapilbarad commented on swagger.yaml
> +  /user:
Should be `/users`

2022-01-04 05:25 UTC, kapilbarad commented on swagger.yaml
> +            $ref: "#/definitions/user"
We should define definitions for Create or Update body separately it should be not just `User` which we will use in responses.

2022-01-04 05:25 UTC, kapilbarad commented on swagger.yaml
> +          description: OK
Description should be `Created`, as it's 201 status code

2022-01-04 05:25 UTC, kapilbarad commented on swagger.yaml
> +            $ref: "#/definitions/user"
Wrong schema.

2022-01-04 05:25 UTC, kapilbarad commented on swagger.yaml
> +            $ref: "#/definitions/user"
No need of schema.

2022-01-04 05:25 UTC, kapilbarad commented on swagger.yaml
> +  /user/reset-password:
This should be actually in Forgot Password API.
Reset Password API should accept Current Password and New Password. if the current Password is valid then update new password.

2022-01-04 05:25 UTC, kapilbarad commented on swagger.yaml
> +    get:
Should be PATCH.

2022-01-04 05:25 UTC, kapilbarad commented on swagger.yaml
> +    post:
This should be under `/user/forgot-password`

2022-01-04 05:25 UTC, kapilbarad commented on swagger.yaml
> +  /user/login:
Path should be `/oauth`

2022-01-04 05:25 UTC, kapilbarad commented on swagger.yaml
> +    get:
Method should be POST as we're creating a new token.

2022-01-04 05:25 UTC, kapilbarad commented on swagger.yaml
> +        - name: "username"
Should be email.

2022-01-04 05:25 UTC, kapilbarad commented on swagger.yaml
> +        "200":
Should be 201

2022-01-04 05:25 UTC, kapilbarad commented on swagger.yaml
> +            $ref: "#/definitions/userLogin"
Definition Name should be OauthToken

2022-01-04 05:25 UTC, kapilbarad commented on swagger.yaml
> +          description: "Tutorial not found"
Wrong Description

2022-01-04 10:16 UTC, kapilbarad requested changes
Please go through all the APIS again and correct the feedbacks.

2022-01-04 10:16 UTC, kapilbarad commented on swagger.yaml
> +    type: apiKey
We should use JWT token in header - Authorization.

2022-01-04 10:16 UTC, kapilbarad commented on swagger.yaml
> +      security:
What about authentication in PATCH and  POST /tutorial?

2022-01-04 10:16 UTC, kapilbarad commented on swagger.yaml
> +            $ref: "#/definitions/userCreated"
Why the name is past sentence `userCreated`, This is request body not the response? Please refer to POST /tutorials API and follow same best practices.

2022-01-04 10:16 UTC, kapilbarad commented on swagger.yaml
> +            $ref: "#/definitions/userCreated"
Please follow definition name practices similar to /tutorial APIs

2022-01-04 10:16 UTC, kapilbarad commented on swagger.yaml
> +            $ref: "#/definitions/userCreated"
Apply the same in other newly added APIs

2022-01-04 10:16 UTC, kapilbarad commented on swagger.yaml
> +      summary: user updated into system
This should be the the description of the API, The action which we're performing not the response.
```
Update user
```

2022-01-04 10:16 UTC, kapilbarad commented on swagger.yaml
> +        "500":
Missing 400 Bad Request response.

2022-01-04 10:16 UTC, kapilbarad commented on swagger.yaml
> +          description: "Invalid user token"
Wrong Description.

2022-01-04 12:34 UTC, JainishaParmar approved these changes

2022-01-04 12:35 UTC, ashishkava approved these changes

2022-01-05 05:18 UTC, kapilbarad requested changes

2022-01-05 05:18 UTC, kapilbarad commented on swagger.yaml
> +    name: access_token
USE `Authorization` header name.

2022-01-05 05:18 UTC, kapilbarad commented on swagger.yaml
> +            $ref: "#/definitions/userCreateBody"
All Definition's name should start with upper case: 'UserCreateBody'.

CC: @JainishaParmar @ashishkava

2022-01-05 05:18 UTC, kapilbarad commented on swagger.yaml
> +          description: created user
Should be `User created`

2022-01-05 05:18 UTC, kapilbarad commented on swagger.yaml
> +          description: "Invalid user details"
Should be Bad Request

2022-01-05 05:18 UTC, kapilbarad commented on swagger.yaml
> +            $ref: "#/definitions/userUpdateBody"
`UserUpdateBody`

2022-01-05 09:20 UTC, JainishaParmar approved these changes

2022-01-05 09:47 UTC, kapilbarad approved these changes

2022-01-05 10:10 UTC, jaimin45 commented
Feat : Apis for user Authentication

2022-01-05 10:10 UTC, merged